import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// esbuild plugin that loads the PDF.js worker source as a text string so it can
// be turned into a Blob URL at runtime. This avoids shipping a separate worker
// file alongside the plugin.
const pdfWorkerAsText = {
	name: "pdf-worker-as-text",
	setup(build) {
		build.onLoad({ filter: /pdf\.worker(\.min)?\.js$/ }, async (args) => {
			const contents = await fs.promises.readFile(args.path, "utf8");
			return { contents, loader: "text" };
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [pdfWorkerAsText],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
