import esbuild from "esbuild";
import process from "process";
import module from "module";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// esbuild plugin that loads the PDF.js worker source as a text string so it can
// be turned into a Blob URL at runtime. This avoids shipping a separate worker
// file alongside the plugin.
const pdfWorkerAsText = {
    name: "pdf-worker-as-text",
    setup(build) {
        build.onLoad({ filter: /pdf\.worker(\.min)?\.js$/ }, async (args) => {
            let contents = await fs.promises.readFile(args.path, "utf8");
            // Replace dynamic <script> element creation in the worker source
            // with a no-op. The worker never runs in a DOM context, so this
            // code path is unreachable, but its presence in the bundled text
            // triggers the Obsidian plugin review scanner.
            contents = contents.replace(
                /document\.createElement\s*\(\s*["']script["']\s*\)/g,
                '(() => { throw new Error("dynamic script loading is not supported"); })()',
            );
            return { contents, loader: "text" };
        });
    },
};

// Strips the dynamic `document.createElement("script")` call from the bundled
// PDF.js library. We supply the worker via a Blob URL, so `loadScript()` is
// dead code, but its presence in the final bundle triggers the Obsidian plugin
// review scanner's "dynamic <script> element creation" check.
const patchPdfjsLoadScript = {
    name: "patch-pdfjs-load-script",
    setup(build) {
        build.onLoad({ filter: /pdfjs-dist[\\/]build[\\/]pdf\.js$/ }, async (args) => {
            let contents = await fs.promises.readFile(args.path, "utf8");
            contents = contents.replace(
                /document\.createElement\s*\(\s*["']script["']\s*\)/g,
                '(() => { throw new Error("dynamic script loading is not supported"); })()',
            );
            return { contents, loader: "js" };
        });
    },
};

const vaultPluginDir = "PDF Extract Test Vault/.obsidian/plugins/pdf-image-extractor";

// After each build, copy the output into the test vault's plugin folder so Obsidian always
// loads the latest code on reload.
const copyToVault = {
    name: "copy-to-vault",
    setup(build) {
        build.onEnd(async () => {
            const outfile = build.initialOptions.outfile;
            if (!outfile) return;
            const dest = `${vaultPluginDir}/${outfile}`;
            await fs.promises.copyFile(outfile, dest).catch(() => {});
            console.log(`Copied ${outfile} --> ${dest}`);
        });
    },
};

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...module.builtinModules,
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    minify: prod,
    plugins: [pdfWorkerAsText, patchPdfjsLoadScript, copyToVault],
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
